project:
  type: website

website:
  title: "Train the Trainer: Student Track Open Science Content"
  page-navigation: true
  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
      - href: help.qmd
        text: Help
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - section: "Template Module"
        contents:
          #- href: materials/OS-template-module/OS-template.qmd
      - section: "Module 1: Open Science Principles"
        contents:
           - href: materials/OS-M1/OS-M1-S0-Module-Intro/OS-M1-S0-Module-Intro.qmd
          #- href: materials/OS-M1/OS-M1-S1-Intro-OS/OS-M1-S1-Intro-OS.qmd
      - section: "Module 2: Open Science Methodological Foundations"
        contents:
          # - href: materials/OS-M2/OS-M2-S0-Module-Intro/OS-M2-S0_Module-Intro.qmd
      - section: "Module 3: Open Science Software Tools"
        contents:
          # - href: materials/OS-M3/OS-M3-S1-Zotero/OS-M3-S1-Zotero.qmd # with template
           - href: materials/OS-M3/OS-M3-S2-R-Part-I/OS-M3-S2-R-Part-I.qmd # work in progress
           - href: materials/OS-M3/OS-M3-S3-R-Part-II/OS-M3-S3-R-Part-II.qmd # work in progress
           - href: materials/OS-M3/OS-M3-S4-Git-RStudio/OS-M3-S4-Git-RStudio.qmd # work in progress
         #  - href: materials/OS-M3/OS-M3-S5-GitHub/OS-M3-S5-GitHub.qmd # work in progress
           - href: materials/OS-M3/OS-M3-S6-Quarto/OS-M3-S6-Quarto.qmd # work in progress
      - section: "Module 4: Open Code and Open Data"
        contents:
      - section: "Module 5: Open Results"
        contents:

format:
  html:
    theme:
      - cosmo
      - brand
    css: website-custom.css
    toc: true
